/* const food = [
    {
        id: 1 , 
        name: 'Fried Rice' ,
        description: 'Hot rice that was fried',
        portion: 1 ,
        price: 2000,
    },
    {
        id: 2 , 
        name: 'Jollof Rice' ,
        description: 'Hot rice that is jollof',
        portion: 1 ,
        price: 1500,
    },
    {
        id: 3 , 
        name: 'Asun' ,
        description: 'Hot goat meat',
        portion: 1 ,
        price: 4000,
    },
    {
        id: 4 , 
        name: 'Pepper Soup' ,
        description: 'Extremely hot pepper soup',
        portion: 1 ,
        price: 3500,
    },
    {
        id: 5 , 
        name: 'Plantain' ,
        description: 'Fried plantain',
        portion: 1 ,
        price: 500,
    },
    {
        id: 6 , 
        name: 'Egusi' ,
        description: 'Egusi soup',
        portion: 1 ,
        price: 900,
    },
    {
        id: 7 , 
        name: 'Ogbno' ,
        description: 'Correct Ogbono Soup',
        portion: 1 ,
        price: 900,
    },
    {
        id: 8 , 
        name: 'Roasted Chicken' ,
        description: ' ',
        portion:  1,
        price: 3800,
    },
    {
        id: 9 , 
        name: 'Fried Chicken' ,
        description: ' ',
        portion: 1,
        price: 2400,
    },
    {
        id: 10 , 
        name: 'Snail' ,
        description: 'Spicy snails',
        portion: 1,
        price: 2500,
    }
];

const resturants = [
    {
        id: 1,
        name:'The Place',
        location: 'Lekki',
        rating: 6/10,
        employees: 10, 
    },
    {
        id: 2,
        name:'Mr Biggs',
        location: 'Ikota',
        rating: 5.5/10,
        employees: 10, 
    },
    {
        id: 3,
        name:'Bukka hut',
        location: 'Festac',
        rating: 7/10,
        employees: 10, 
    },
    {
        id: 4,
        name:'Shiro Lagos',
        location: 'Victoria Island',
        rating: 9/10,
        employees: 10, 
    },
    {
        id: 5,
        name:'Cactus Restaurant',
        location: '20/24 Ozumba Mbadiwe Ave',
        rating: 8/10,
        employees: 10, 
    },
    {
        id: 6,
        name:'Bungalow Restaurant',
        location: 'Victoria Island',
        rating: 7.5/10,
        employees: 10, 
    },
    {
        id: 7,
        name:'Talindo Steak House',
        location: '7B Karimu Kotun St',
        rating: 8/10,
        employees: 10, 
    },
    {
        id: 8,
        name:'Ocean Basket Victoria Island',
        location: '35 Akin Adesola St',
        rating: 8/10,
        employees: 10, 
    },
    {
        id: 9,
        name:'De Bull Restaurant & Bar',
        location: 'Ikeja',
        rating: 9.5/10,
        employees: 10, 
    },
    {
        id: 10,
        name:'Danfo Bistro',
        location: 'Ikoyi',
        rating: 7/10,
        employees: 10, 
    }
]

const employees =[
    {
        id: 1,
        name: 'John Doe',
        nationality: 'Croatian',
        state: 'Dalmatia',
        gender: Male,
        dateEmployed: '1/10/2018',
        status: 'Married',
    },
    {
        id: 2,
        name: 'Daniel Sinjen',
        nationality: 'Nigerian',
        state: 'Taraba',
        gender: Male,
        dateEmployed: '2/7/2022',
        status: 'Single',
    },
    {
        id: 3,
        name: 'Tobe Nwachukwu',
        nationality: 'Nigerian',
        state: 'Abia',
        gender: 'Male',
        dateEmployed: '30/12/2007',
        status: 'Married',
    },
    {
        id: 4,
        name: 'Susan Peters',
        nationality: 'American',
        state: 'Texas',
        gender: 'Female',
        dateEmployed: '20/4/2017',
        status: 'Married',
    },
    {
        id: 5,
        name: 'Steve Jobs',
        nationality: 'American',
        state: 'California',
        gender: 'Male',
        dateEmployed: '19/8/2020',
        status: 'Single',
    },
    {
        id: 6,
        name: 'Monika Emma',
        nationality: 'Russian',
        state: 'Astrakhan',
        gender: 'Female',
        dateEmployed:'20/5/2018' ,
        status: 'Single',
    },
    {
        id: 7,
        name: 'Mia Issabelle',
        nationality: 'American',
        state: 'Dallas',
        gender: 'Female',
        dateEmployed: '11/6/2019',
        status: 'Single',
    },
    {
        id: 8,
        name: 'Michael Stones',
        nationality: 'Jamaican',
        state: 'Cornwall',
        gender: 'Male',
        dateEmployed: '1/10/2006',
        status: 'Married',
    },
    {
        id: 9,
        name: 'Elizabeth Westbrook',
        nationality: 'Scot',
        state: 'Glasgow',
        gender: 'Female',
        dateEmployed: '19/5/2022',
        status: 'Married',
    },
    {
        id: 10,
        name: 'Favour Masu',
        nationality: 'Arabian',
        state: 'Dublin',
        gender: 'Female',
        dateEmployed: '21/7/2019',
        status: 'Single',
    }
]

module.exports = {
    food, employees, resturants
}

*/
